### ISSUE TITLE
安装出错，neovim 0.10

### ISSUE THREAD

**Issue by Learner-Geek-Perfectionist** [minhanghuang/nvim#26]
错误一：
[NvimTree]
Unknown option: view.mappings
see :help nvim-tree-opts for available configuration options
Press ENTER or tvpe command to continue
错误二：
![image](https://github.com/minhanghuang/nvim/assets/48880596/b876929a-77e9-4b8f-b459-28c4cd926878)

**Comment by minhanghuang** [comment]
错误一是nvim-tree.lua版本更新后接口不向下兼容的问题, 你可以指定一下nvim-tree.lua的版本`b601b5a`, 这个问题最近我也在更新配置, 在这个分支上: https://github.com/minhanghuang/nvim/tree/update-nvim-tree
