### ISSUE TITLE
安装出错，plugin.dir不存在，neovim0.10

### ISSUE THREAD

**Issue by Learner-Geek-Perfectionist** [minhanghuang/nvim#28]
![image](https://github.com/minhanghuang/nvim/assets/48880596/53c3368e-8fef-4bb5-86eb-099824a19d6c)

**Comment by minhanghuang** [comment]
Hi @Learner-Geek-Perfectionist, 可以尝试更新一下`lazy.nvim`版本, 类似问题: [https://github.com/folke/lazy.nvim/issues/241](https://github.com/folke/lazy.nvim/issues/241)

**Comment by Learner-Geek-Perfectionist** [comment]
请问有稳定可用的版本吗？

**Comment by minhanghuang** [comment]
我本地Ubuntu20.04用的是`96584866b9c5e998cbae300594d0ccfd0c464627`这个版本, 你切换到这个版本试一试

**Comment by Learner-Geek-Perfectionist** [comment]
请问是https://github.com/minhanghuang/nvim这个仓库的96584866b9c5e998cbae300594d0ccfd0c464627哈希提交吗？我git clone该仓库， 然后   git show 96584866b9c5e998cbae300594d0ccfd0c464627，并没有找到这个提交版本。

**Comment by Learner-Geek-Perfectionist** [comment]
请问是  https://github.com/minhanghuang/nvim   这个 仓库的哈希提交吗？
我git clone 这个仓库，然后    git show 96584866b9c5e998cbae300594d0ccfd0c464627

并没有找到该提交记录。

**Comment by Learner-Geek-Perfectionist** [comment]
我注意到lock.json的commit就是96584866b9c5e998cbae300594d0ccfd0c464627，这意味着：您的本地lazy.nvim版本和您仓库的lazy.nvim版本一样？？

我取消了浅克隆，即：
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  require('user.colorscheme'),
  require('user.conf'),
  require('user.lsp'),
  require('user.cmp'),
  require('user.dap'),
})

require("user.config"):load()

所以，lazy.nvim的问题解决了。



但是它提示我：
![image](https://github.com/minhanghuang/nvim/assets/48880596/0750df2d-a3f5-4427-9d57-e2ba91547b2e)

请问您本地使用的neovim的版本是多少呢？

我的是0.10，另外您仓库有没有稳定可以用的配置？

**Comment by minhanghuang** [comment]
```
NVIM v0.10.0-dev-2175+gc8a27bae3
Build type: RelWithDebInfo
LuaJIT 2.1.1706032906
Run "nvim -V1 -v" for more info
```
我的Neovim版本。这个看着是`telescope.nvim`的报错, 进入`~/.local/share/nvim/lazy/telescope.nvim`看看版本和`lazy-lock.json`是否一致

**Comment by Learner-Geek-Perfectionist** [comment]
请问有没有开箱即用的cpp配置项目呢？俺也想在nvim下愉快地写cpp，但是好用的cpp配置项目几乎没有。

**Comment by minhanghuang** [comment]
> 请问有没有开箱即用的cpp配置项目呢？俺也想在nvim下愉快地写cpp，但是好用的cpp配置项目几乎没有。

Neovim需要折腾的东西挺多的, Neovim版本升级和plugin升级可能都会导致Neovim无法打开。经常需要修修补补, 不太可能一劳永逸, 你可以选择一些已经写好的配置并且有人长期跟进维护的; [LazyVim](https://github.com/LazyVim/LazyVim)  [NvChad](https://github.com/NvChad/NvChad) 或者在VSCode上配置Neovim
